const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_18_14_09_25_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTI4LFxuICAgICAgICA1NyxcbiAgICAgICAgMTYwLFxuICAgICAgICA2NSxcbiAgICAgICAgMjA4LFxuICAgICAgICAxMTIsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMTMwLFxuICAgICAgICAxNzAsXG4gICAgICAgIDc2LFxuICAgICAgICA0NSxcbiAgICAgICAgMTkxLFxuICAgICAgICA4NyxcbiAgICAgICAgMTAxLFxuICAgICAgICA1MixcbiAgICAgICAgMjA5LFxuICAgICAgICAxMDEsXG4gICAgICAgIDIwNixcbiAgICAgICAgOTUsXG4gICAgICAgIDE1NSxcbiAgICAgICAgMTYsXG4gICAgICAgIDc4LFxuICAgICAgICA3OSxcbiAgICAgICAgMjU1LFxuICAgICAgICAyMzIsXG4gICAgICAgIDQ2LFxuICAgICAgICA3MyxcbiAgICAgICAgMjAwLFxuICAgICAgICAyLFxuICAgICAgICAxMjQsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMTE3XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDU5LFxuICAgICAgICAyNTIsXG4gICAgICAgIDI0OSxcbiAgICAgICAgNSxcbiAgICAgICAgMTU3LFxuICAgICAgICAxMjksXG4gICAgICAgIDEwMSxcbiAgICAgICAgNzgsXG4gICAgICAgIDE0NSxcbiAgICAgICAgMzcsXG4gICAgICAgIDIxMSxcbiAgICAgICAgMTc5LFxuICAgICAgICAyNDQsXG4gICAgICAgIDE2MCxcbiAgICAgICAgMTI3LFxuICAgICAgICA4NyxcbiAgICAgICAgMTk5LFxuICAgICAgICA3OCxcbiAgICAgICAgMTUxLFxuICAgICAgICAxMzcsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMTIyLFxuICAgICAgICAxNzQsXG4gICAgICAgIDIzNixcbiAgICAgICAgMjIsXG4gICAgICAgIDMyLFxuICAgICAgICA1MyxcbiAgICAgICAgMTM4LFxuICAgICAgICAyMTcsXG4gICAgICAgIDIwMixcbiAgICAgICAgMTMxLFxuICAgICAgICAxOFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjE2LFxuICAgICAgICAxODAsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMTQyLFxuICAgICAgICAyMDYsXG4gICAgICAgIDg5LFxuICAgICAgICAxMTQsXG4gICAgICAgIDEyNSxcbiAgICAgICAgNTgsXG4gICAgICAgIDg5LFxuICAgICAgICAxMDUsXG4gICAgICAgIDQyLFxuICAgICAgICAyMTQsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMTUwLFxuICAgICAgICAyNTEsXG4gICAgICAgIDE2MCxcbiAgICAgICAgMTQ2LFxuICAgICAgICAyNDAsXG4gICAgICAgIDE2NCxcbiAgICAgICAgODUsXG4gICAgICAgIDIzNSxcbiAgICAgICAgMTczLFxuICAgICAgICA3MixcbiAgICAgICAgMjU1LFxuICAgICAgICAxNTIsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMTgsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMTcxLFxuICAgICAgICAxMixcbiAgICAgICAgMTIzXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE1NCxcbiAgICAgICAgMixcbiAgICAgICAgMTMsXG4gICAgICAgIDYxLFxuICAgICAgICAyNTUsXG4gICAgICAgIDY5LFxuICAgICAgICAyNTAsXG4gICAgICAgIDIwMSxcbiAgICAgICAgOTUsXG4gICAgICAgIDI0LFxuICAgICAgICAyMyxcbiAgICAgICAgMjE0LFxuICAgICAgICAxMDYsXG4gICAgICAgIDg4LFxuICAgICAgICAxODcsXG4gICAgICAgIDYzLFxuICAgICAgICAyNTUsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMzksXG4gICAgICAgIDEyMixcbiAgICAgICAgMTk5LFxuICAgICAgICAyMjYsXG4gICAgICAgIDU0LFxuICAgICAgICAxNDksXG4gICAgICAgIDIwMSxcbiAgICAgICAgNDQsXG4gICAgICAgIDQyLFxuICAgICAgICAxNTEsXG4gICAgICAgIDUwLFxuICAgICAgICAyMDUsXG4gICAgICAgIDczLFxuICAgICAgICA2NlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTYsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMjI0LFxuICAgICAgICA0MyxcbiAgICAgICAgOTgsXG4gICAgICAgIDEwOCxcbiAgICAgICAgMTU1LFxuICAgICAgICAzLFxuICAgICAgICA4MCxcbiAgICAgICAgMTY1LFxuICAgICAgICAxODUsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMTM4LFxuICAgICAgICAxMDIsXG4gICAgICAgIDM3LFxuICAgICAgICAxNzMsXG4gICAgICAgIDMxLFxuICAgICAgICA4NixcbiAgICAgICAgMjM2LFxuICAgICAgICAxMDQsXG4gICAgICAgIDEzNixcbiAgICAgICAgMTYsXG4gICAgICAgIDAsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMzMsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMTE3LFxuICAgICAgICAxNjMsXG4gICAgICAgIDE2NSxcbiAgICAgICAgMjAzLFxuICAgICAgICAxMjIsXG4gICAgICAgIDExM1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMTQsXG4gICAgICAgIDE2NCxcbiAgICAgICAgMTQsXG4gICAgICAgIDY2LFxuICAgICAgICAxNDQsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMTE5LFxuICAgICAgICAxODAsXG4gICAgICAgIDEwLFxuICAgICAgICAxOTIsXG4gICAgICAgIDg1LFxuICAgICAgICAyMjQsXG4gICAgICAgIDE0NixcbiAgICAgICAgMTYzLFxuICAgICAgICA1OSxcbiAgICAgICAgMTU1LFxuICAgICAgICAxNDMsXG4gICAgICAgIDYxLFxuICAgICAgICAxNzksXG4gICAgICAgIDM4LFxuICAgICAgICAyMjAsXG4gICAgICAgIDIxNCxcbiAgICAgICAgMTI2LFxuICAgICAgICAxMTEsXG4gICAgICAgIDg3LFxuICAgICAgICAxMjQsXG4gICAgICAgIDExOCxcbiAgICAgICAgOTUsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMTAsXG4gICAgICAgIDE2MSxcbiAgICAgICAgODNcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNTYsXG4gICAgICAgICAgNjgsXG4gICAgICAgICAgMTU0LFxuICAgICAgICAgIDg1LFxuICAgICAgICAgIDYsXG4gICAgICAgICAgMTQ3LFxuICAgICAgICAgIDE1LFxuICAgICAgICAgIDEyLFxuICAgICAgICAgIDUxLFxuICAgICAgICAgIDEwNyxcbiAgICAgICAgICA5NSxcbiAgICAgICAgICAxOTUsXG4gICAgICAgICAgMTEwLFxuICAgICAgICAgIDE3MyxcbiAgICAgICAgICAxNTAsXG4gICAgICAgICAgMjA5LFxuICAgICAgICAgIDY2LFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDc5LFxuICAgICAgICAgIDIyNCxcbiAgICAgICAgICAxNzQsXG4gICAgICAgICAgMjAwLFxuICAgICAgICAgIDIyMSxcbiAgICAgICAgICA1LFxuICAgICAgICAgIDE3MixcbiAgICAgICAgICAzNixcbiAgICAgICAgICA2NSxcbiAgICAgICAgICAxOTAsXG4gICAgICAgICAgMTg0LFxuICAgICAgICAgIDcwLFxuICAgICAgICAgIDE5NyxcbiAgICAgICAgICAxMDJcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMzQsXG4gICAgICAgICAgMjEwLFxuICAgICAgICAgIDI1MyxcbiAgICAgICAgICAxODcsXG4gICAgICAgICAgMTA2LFxuICAgICAgICAgIDc1LFxuICAgICAgICAgIDIxOCxcbiAgICAgICAgICAxODcsXG4gICAgICAgICAgMTExLFxuICAgICAgICAgIDY1LFxuICAgICAgICAgIDcyLFxuICAgICAgICAgIDIwNixcbiAgICAgICAgICAyMDksXG4gICAgICAgICAgNzcsXG4gICAgICAgICAgNDQsXG4gICAgICAgICAgMjQyLFxuICAgICAgICAgIDE2MyxcbiAgICAgICAgICAxNDgsXG4gICAgICAgICAgNDcsXG4gICAgICAgICAgMTE5LFxuICAgICAgICAgIDE5MixcbiAgICAgICAgICAyMTEsXG4gICAgICAgICAgMjI5LFxuICAgICAgICAgIDEzMSxcbiAgICAgICAgICAyMTEsXG4gICAgICAgICAgODQsXG4gICAgICAgICAgMTg4LFxuICAgICAgICAgIDE5OCxcbiAgICAgICAgICAyNTQsXG4gICAgICAgICAgMTYwLFxuICAgICAgICAgIDIzMyxcbiAgICAgICAgICAyOVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDExMixcbiAgICAgICAgOTUsXG4gICAgICAgIDE3NyxcbiAgICAgICAgMTE0LFxuICAgICAgICAyMjUsXG4gICAgICAgIDE5OCxcbiAgICAgICAgMjAxLFxuICAgICAgICA3NyxcbiAgICAgICAgMTM4LFxuICAgICAgICAzNCxcbiAgICAgICAgMTg4LFxuICAgICAgICA3OSxcbiAgICAgICAgMTQwLFxuICAgICAgICAxMDUsXG4gICAgICAgIDk2LFxuICAgICAgICAxMjQsXG4gICAgICAgIDQ4LFxuICAgICAgICAxMTEsXG4gICAgICAgIDE1MixcbiAgICAgICAgMTQ1LFxuICAgICAgICA1MyxcbiAgICAgICAgMyxcbiAgICAgICAgMTUyLFxuICAgICAgICAxNzIsXG4gICAgICAgIDI0LFxuICAgICAgICAyOSxcbiAgICAgICAgNDgsXG4gICAgICAgIDc4LFxuICAgICAgICA5NCxcbiAgICAgICAgMjM0LFxuICAgICAgICAxMzMsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMjIsXG4gICAgICAgIDE1NixcbiAgICAgICAgMjAzLFxuICAgICAgICAyMjksXG4gICAgICAgIDk0LFxuICAgICAgICAyMzgsXG4gICAgICAgIDIzMCxcbiAgICAgICAgNDYsXG4gICAgICAgIDEwMSxcbiAgICAgICAgOTQsXG4gICAgICAgIDk2LFxuICAgICAgICAyMzYsXG4gICAgICAgIDc0LFxuICAgICAgICA2NCxcbiAgICAgICAgNTIsXG4gICAgICAgIDEzMixcbiAgICAgICAgMTYzLFxuICAgICAgICAxOCxcbiAgICAgICAgMzQsXG4gICAgICAgIDIwMCxcbiAgICAgICAgMzEsXG4gICAgICAgIDQsXG4gICAgICAgIDIxOCxcbiAgICAgICAgNzcsXG4gICAgICAgIDM0LFxuICAgICAgICAyNTAsXG4gICAgICAgIDgxLFxuICAgICAgICAxMTUsXG4gICAgICAgIDI0NSxcbiAgICAgICAgNzEsXG4gICAgICAgIDIyLFxuICAgICAgICAxMFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogMjAzLFxuICBcImFkdlNlY3JldEtleVwiOiBcIkhWNWlVWUtqdWU1T0hxamNmZGxUQ3Rxa2JiTzJNT0grRlVvNlk2ZjFFczA9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiMjM0ODEzODA5MzA4OEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiMDhEQTU5NzA2OUFGNUQ5RTQyRDc0MzM1NzAzMUIwRkRcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzI3Mjg4MDgzXG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMSxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcIjEzWEU4QkJwUzdhaGJVbkhoVDh6NndcIixcbiAgXCJwaG9uZUlkXCI6IFwiNWY0MjU5ZWItNmI5OC00ZDgxLWFhZWUtYmQ5YTMxNzE5N2E0XCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDU2LFxuICAgICAgNDUsXG4gICAgICAxMTksXG4gICAgICAyNixcbiAgICAgIDE0OCxcbiAgICAgIDIyOCxcbiAgICAgIDc0LFxuICAgICAgMTMzLFxuICAgICAgMTE2LFxuICAgICAgMTE0LFxuICAgICAgMTM3LFxuICAgICAgMTgwLFxuICAgICAgNixcbiAgICAgIDgsXG4gICAgICAxNDAsXG4gICAgICA2MyxcbiAgICAgIDcyLFxuICAgICAgMjQyLFxuICAgICAgMixcbiAgICAgIDE5NFxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IHRydWUsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxMTksXG4gICAgICAyMTksXG4gICAgICAxMixcbiAgICAgIDEzNixcbiAgICAgIDE4MyxcbiAgICAgIDIwMCxcbiAgICAgIDIwLFxuICAgICAgMTYwLFxuICAgICAgMjIyLFxuICAgICAgMTg4LFxuICAgICAgMjQzLFxuICAgICAgMjA4LFxuICAgICAgMTIyLFxuICAgICAgMjQ4LFxuICAgICAgMTIsXG4gICAgICA3NixcbiAgICAgIDE1MixcbiAgICAgIDIwMixcbiAgICAgIDEwMixcbiAgICAgIDIzM1xuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwicGFpcmluZ0NvZGVcIjogXCJBTFg0NE1ZTFwiLFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiMjM0ODEzODA5MzA4ODo5QHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJuYW1lXCI6IFwiTXVoYWJhcyBhcnRzIGFuZCBjcmFmdHNcIixcbiAgICBcImxpZFwiOiBcIjEyODAwMzMyOTc3NzY3MTo5QGxpZFwiXG4gIH0sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ0t5VHdPSUJFSWltMGJjR0dBRWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiSFlaVFcyMTlVb0hqdnIzNVB4WS8zbUN1Zy9mVEU3OUgvSHA0d1pGMnJGZz1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCI1dnQwOWV3MjhKNW8xM3VGQmRBaWJyVm9pS0h0aDlwNjQyNHNDLzQ3Nm80TlJBdFJVZlJjM01IaFpZN2REZmNadUJlSnVlcVV1UGZ2UVB6aGFoTTlDdz09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCI5Vkd4OFdzaUdObm5jMWo5MWp5TXBRT3ZyT3ZnNmhkL1pWa3pQTDlYOWtwWGVDcHJBK2VrOUp2aUVrNnB2K3V5R200SDRCMXVnaWt1TlBGVHl6alBEUT09XCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCIyMzQ4MTM4MDkzMDg4OjlAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAyOSxcbiAgICAgICAgICAxMzQsXG4gICAgICAgICAgODMsXG4gICAgICAgICAgOTEsXG4gICAgICAgICAgMTA5LFxuICAgICAgICAgIDEyNSxcbiAgICAgICAgICA4MixcbiAgICAgICAgICAxMjksXG4gICAgICAgICAgMjI3LFxuICAgICAgICAgIDE5MCxcbiAgICAgICAgICAxODksXG4gICAgICAgICAgMjQ5LFxuICAgICAgICAgIDYzLFxuICAgICAgICAgIDIyLFxuICAgICAgICAgIDYzLFxuICAgICAgICAgIDIyMixcbiAgICAgICAgICA5NixcbiAgICAgICAgICAxNzQsXG4gICAgICAgICAgMTMxLFxuICAgICAgICAgIDI0NyxcbiAgICAgICAgICAyMTEsXG4gICAgICAgICAgMTksXG4gICAgICAgICAgMTkxLFxuICAgICAgICAgIDcxLFxuICAgICAgICAgIDI1MixcbiAgICAgICAgICAxMjIsXG4gICAgICAgICAgMTIwLFxuICAgICAgICAgIDE5MyxcbiAgICAgICAgICAxNDUsXG4gICAgICAgICAgMTE4LFxuICAgICAgICAgIDE3MixcbiAgICAgICAgICA4OFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwic21iYVwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzI3Mjg4MDc2LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBRFhOXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFEWE4uanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJMVXJmTkVWTHI3R1lrZXdFNjRoU0xwaWU4dk1vMWhQOGVjOS80QmlHaGZRPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjQ3NTAwNzQwNCxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzI3Mjg4MDgxMjk3XCJ9Igp9",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
